# Generated by Django 3.0.4 on 2020-03-06 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 7, 34, 49, 110557, tzinfo=utc)),
        ),
    ]
