# Generated by Django 3.0.4 on 2020-03-06 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200306_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 7, 39, 42, 555474, tzinfo=utc)),
        ),
    ]
